apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: cleanup-completed-pods
  name: cleanup-completed-pods
  namespace: argo
spec:
  schedule: "0 0 * * 1"
  jobTemplate:
     metadata:
       labels:
         app: cleanup-completed-pods
     spec:
      template:
        metadata:
          labels:
            app: cleanup-completed-pods
        spec:
          serviceAccountName: cleanup-completed-pods
          containers:
          - name: cleanup-completed-pods
            image: bouwe/cleanup-completed-pods:0.0.2
            env:
            - name: NAMESPACE
              value: argo
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 10m
                memory: 10Mi
          restartPolicy: OnFailure
