apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: argo
  name: cleanup-completed-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cleanup-completed-pods
subjects:
- kind: ServiceAccount
  name: cleanup-completed-pods
  namespace: argo

